# Generated by Django 4.0.4 on 2022-05-18 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_method', models.CharField(max_length=150)),
                ('card_number', models.CharField(max_length=150)),
                ('cardholders_name', models.CharField(max_length=150)),
                ('card_expiring_date', models.DateField()),
                ('cvv', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments_infos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
